name: DiscordPlugin
main: pw.byakuren.discordplugin.DiscordPlugin
description: "Connect a discord channel to your minecraft server!"
author: "Brod8362"
version: "1.0"
commands:
  test:
    description: "Testing command"